export const jobs = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "Stripe",
    location: "Remote (US)",
    type: "Full-time",
    salary: "$160k – $200k",
    tags: ["React", "TypeScript", "GraphQL"],
    postedAt: "2 days ago",
    logo: "https://ui-avatars.com/api/?name=Stripe&background=635BFF&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Stripe is looking for a Senior Frontend Engineer to join our Payments UI team. You'll work on the interfaces that millions of businesses use to accept payments, manage subscriptions, and analyze revenue. In this role you'll collaborate closely with product designers, backend engineers, and fellow frontend engineers to ship high-quality, accessible web experiences. We value engineers who think holistically about product problems and can turn complex financial data into intuitive, delightful interfaces. You'll champion performance, maintainability, and scalability in our React + TypeScript codebase. Strong knowledge of GraphQL and experience with design systems is a big plus.",
  },
  {
    id: 2,
    title: "Staff Software Engineer — Infrastructure",
    company: "Vercel",
    location: "Remote (Worldwide)",
    type: "Full-time",
    salary: "$180k – $230k",
    tags: ["Node.js", "Rust", "Kubernetes", "Edge Computing"],
    postedAt: "1 day ago",
    logo: "https://ui-avatars.com/api/?name=Vercel&background=000000&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Join Vercel's Infrastructure team to shape the edge network that powers millions of deployments daily. As a Staff Engineer you'll own large technical initiatives from design to production, mentor senior engineers, and drive architectural decisions across the compute and networking layers. You'll work on build systems, CDN internals, and our Rust-powered edge runtime. You're comfortable writing production-quality code, leading technical reviews, and communicating complex trade-offs to cross-functional stakeholders. Experience with distributed systems, low-latency networking, or WebAssembly runtimes is highly desirable.",
  },
  {
    id: 3,
    title: "Product Designer — Design Systems",
    company: "Linear",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$140k – $170k",
    tags: ["Figma", "Design Systems", "Prototyping", "CSS"],
    postedAt: "3 days ago",
    logo: "https://ui-avatars.com/api/?name=Linear&background=5E6AD2&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Linear is seeking a Product Designer focused on our design system to maintain and evolve the visual language used across our entire product. You'll work directly with our small product and engineering team to create reusable components, document usage guidelines, and raise the quality bar for every interaction. The ideal candidate has a deep obsession with craft — pixel-level precision, thoughtful motion, and accessible component design are non-negotiable for you. You'll own the Figma component library and collaborate with engineers to ensure faithful implementation in our React codebase.",
  },
  {
    id: 4,
    title: "Machine Learning Engineer",
    company: "Figma",
    location: "New York, NY",
    type: "Full-time",
    salary: "$170k – $210k",
    tags: ["Python", "PyTorch", "LLMs", "Computer Vision"],
    postedAt: "5 days ago",
    logo: "https://ui-avatars.com/api/?name=Figma&background=F24E1E&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Figma's AI team is hiring a Machine Learning Engineer to work on features that help designers move faster and smarter. You'll train and ship models that power capabilities like auto-layout suggestions, image generation, and intelligent search. You'll work alongside product managers and researchers to define the roadmap, prototype ideas rapidly, and integrate models into production systems serving tens of millions of users. Strong Python and PyTorch skills are required; experience with vision-language models or generative AI is a strong advantage.",
  },
  {
    id: 5,
    title: "Backend Engineer — Search",
    company: "Notion",
    location: "Remote (US & Canada)",
    type: "Full-time",
    salary: "$150k – $185k",
    tags: ["Go", "Elasticsearch", "PostgreSQL", "Kafka"],
    postedAt: "1 week ago",
    logo: "https://ui-avatars.com/api/?name=Notion&background=191919&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Notion is hiring a Backend Engineer to help us build the world's best search experience across notes, databases, and connected tools. You'll design and optimise the indexing pipeline, improve relevance ranking, and scale search to handle Notion's rapidly growing user base. Our search stack is built on Elasticsearch with a Go service layer and event streaming via Kafka. You'll own full features end-to-end, participate in on-call rotations, and partner closely with the data platform and product teams. Experience with information retrieval, NLP, or large-scale distributed systems is a major plus.",
  },
  {
    id: 6,
    title: "Developer Advocate",
    company: "GitHub",
    location: "Remote (Global)",
    type: "Full-time",
    salary: "$130k – $160k",
    tags: ["GitHub Actions", "DevOps", "Technical Writing", "Community"],
    postedAt: "4 days ago",
    logo: "https://ui-avatars.com/api/?name=GitHub&background=24292F&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "GitHub is looking for a Developer Advocate to champion our developer tools and grow our open-source community. You'll create technical content — blog posts, video tutorials, live streams, and conference talks — that help developers get the most out of GitHub Actions, Codespaces, and Copilot. You'll travel to events, gather product feedback, and serve as the voice of the developer community inside GitHub. The ideal candidate is an experienced developer who is comfortable on a stage, a prolific writer, and genuinely passionate about open-source software and developer productivity.",
  },
  {
    id: 7,
    title: "Security Engineer — Product Security",
    company: "Cloudflare",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$145k – $185k",
    tags: ["AppSec", "Threat Modeling", "Rust", "Zero Trust"],
    postedAt: "6 days ago",
    logo: "https://ui-avatars.com/api/?name=Cloudflare&background=F48120&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Cloudflare's Product Security team is looking for a Security Engineer to help us secure the products and infrastructure that protect millions of websites worldwide. You'll conduct security reviews, threat model new features, perform penetration testing, and work with engineering teams to remediate vulnerabilities. You'll also help build security tooling and automation to scale our review processes. We value engineers who can think like an attacker, communicate risks clearly to non-security stakeholders, and build trusted relationships across engineering teams. Experience with Zero Trust architectures or network security is a plus.",
  },
  {
    id: 8,
    title: "iOS Engineer — Commerce",
    company: "Shopify",
    location: "Remote (Canada)",
    type: "Full-time",
    salary: "$140k – $175k CAD",
    tags: ["Swift", "SwiftUI", "Objective-C", "Mobile"],
    postedAt: "2 weeks ago",
    logo: "https://ui-avatars.com/api/?name=Shopify&background=96BF48&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "Shopify is hiring an iOS Engineer to work on our merchant-facing mobile apps, used by over 2 million businesses to run their stores on the go. You'll build new features in SwiftUI, maintain existing Objective-C code, and contribute to our shared component library. You'll collaborate with product designers on motion and interaction details, and with backend engineers to design clean API contracts. We're looking for someone with a strong eye for UI quality, solid understanding of iOS SDK internals, and passion for shipping great experiences to real merchants.",
  },
  {
    id: 9,
    title: "Site Reliability Engineer",
    company: "MongoDB",
    location: "Dublin, Ireland",
    type: "Full-time",
    salary: "€95k – €130k",
    tags: ["Kubernetes", "Terraform", "Python", "Observability"],
    postedAt: "3 days ago",
    logo: "https://ui-avatars.com/api/?name=MongoDB&background=00ED64&color=001E2B&size=64&bold=true&font-size=0.4",
    description:
      "MongoDB Atlas, our fully managed cloud database, serves hundreds of thousands of customers globally. We're hiring an SRE to help us ensure Atlas is fast, reliable, and available. You'll manage Kubernetes clusters across AWS, GCP, and Azure, build and maintain Terraform modules, set up observability stacks (Prometheus, Grafana, OpenTelemetry), and respond to incidents. You'll work closely with the Atlas engineering teams to improve reliability from the design phase. We're looking for someone with strong Linux fundamentals, automation mindset, and the ability to stay calm under pressure.",
  },
  {
    id: 10,
    title: "Senior Software Engineer — Metrics Platform",
    company: "Datadog",
    location: "Paris, France",
    type: "Full-time",
    salary: "€90k – €125k",
    tags: ["Go", "Apache Kafka", "ClickHouse", "Data Engineering"],
    postedAt: "5 days ago",
    logo: "https://ui-avatars.com/api/?name=Datadog&background=632CA6&color=fff&size=64&bold=true&font-size=0.4",
    description:
      "The Metrics Platform team at Datadog ingests and processes trillions of data points every day. We're looking for a Senior Software Engineer to help us evolve our high-throughput Go services, improve the reliability of our Kafka-based ingestion pipeline, and scale our ClickHouse analytics layer. You'll own large features from architecture to production, drive performance improvements through profiling and benchmarking, and mentor junior engineers. You'll work in a fast-paced, data-intensive environment where your decisions have direct impact on product quality for thousands of enterprise customers.",
  },
];
